apiVersion: v1
data:
  teleport.yaml: |
    teleport:
      auth_token: foo
      log:
        output: stderr
        severity: INFO
      data_dir: /var/lib/teleport
      auth_servers:
        -  teletest.nicklaassen.ca:443
    auth_service:
      enabled: no
    ssh_service:
      enabled: yes
      listen_addr: 0.0.0.0:3022
    proxy_service:
      enabled: no
kind: ConfigMap
metadata:
  labels:
    app: teleport-node
  name: node-config
  namespace: default
