apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teleport-node
  name: test-deployment
  namespace: default
spec:
  replicas: 12
  selector:
    matchLabels:
      app: teleport-node
  template:
    metadata:
      labels:
        app: teleport-node
    spec:
      containers:
      - image: quay.io/gravitational/teleport:7.0.3
        args: ["-d", "--insecure"]
        name: loadtest
        ports:
        - containerPort: 3022
          name: nodessh
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/teleport
          name: config
          readOnly: true
        - mountPath: /var/lib/teleport
          name: storage
      volumes:
      - configMap:
          name: node-config
        name: config
      - emptyDir: {}
        name: storage
