teleport:
  nodename: one-proxy-1
  log:
    output: stderr
    severity: DEBUG

  data_dir: ./data/proxy

  auth_token: "foo"

  auth_servers:
  - nic-hsm-auth-4a8974828932d75c.elb.us-west-2.amazonaws.com:3025

auth_service:
  enabled: no

ssh_service:
  enabled: no

proxy_service:
  enabled: yes
  public_addr: 
  - teletest.nicklaassen.ca:443

  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  web_listen_addr: 0.0.0.0:443
  acme:
    enabled: yes
    email: nic@nicklaassen.ca
