# Single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
teleport:
  nodename: auth-1
  log:
    output: stderr
    severity: DEBUG

  data_dir: data/auth

  storage:
    type: dynamodb
    region: us-west-2
    table_name: "nic-hsm"

auth_service:
  enabled: yes

  cluster_name: teletest.nicklaassen.ca

  authentication:
    type: local
    second_factor: off

  tokens:
  - node,proxy,app,kube:foo

  listen_addr: 0.0.0.0:3025

  ca_key_params:
    pkcs11:
      module_path: /opt/cloudhsm/lib/libcloudhsm_pkcs11.so
      token_label: cavium
      pin: "teleport_user:Thirtyseven37"

ssh_service:
  enabled: no

proxy_service:
  enabled: no
