version: v3
teleport:
  nodename: one-node-iot
  log:
    output: stderr
    severity: DEBUG

  data_dir: ./data/one-node-iot

  auth_token: "foo"
    #join_params:
    #  method: iam
    #  token_name: iam-token

  proxy_server: https://one:4080

auth_service:
  enabled: no

proxy_service:
  enabled: no

ssh_service:
  enabled: yes
  labels:
    owner: db-admins
    test: test
    env: prod

  commands:
  - name: date
    command: ["date"]
    period: 1m
  - name: hostname
    command: [hostname]
    period: 1m

app_service:
  enabled: yes
  debug_app: true
  apps:
    - name: "httpbin"
      uri: "http://localhost:80"

kubernetes_service:
  enabled: no
  kubeconfig_file: /Users/nklaassen/src/teletest/kube/config

db_service:
  enabled: yes
  resources:
    - labels:
        "*": "*"

windows_desktop_service:
  enabled: no
  ldap:
    # Address of the LDAP server for secure LDAP connections.
    # Usually, this address will use port 636, like: ldap.example.com:636.
    # For best results, this address should point to a highly-available
    # endpoint (a load balancer, VIP, or round-robin DNS) rather than
    # a single domain controller.
    addr: 'ldap.example.com:636'
    # Active Directory domain name you are connecting to.
    domain: 'example.com'
    # LDAP username for authentication. This username must include the domain
    # NetBIOS name. The use of single quotes here is intentional in order to
    # avoid the need to escape the backslash (\) character.
    #
    # For example, if your domain is "example.com", the NetBIOS name for it is
    # likely "EXAMPLE". When connecting as the "svc-teleport" user, you should
    # use the format: "EXAMPLE\svc-teleport".
    username: 'example'
    # DER encoded LDAP CA certificate.
    # der_ca_file: /tmp/crt
  # (optional) hosts is a list of hostnames to register as WindowsDesktop
  # objects in Teleport.
  hosts:
    - win1.example.com
    - win2.example.com
