teleport:
  nodename: one-kube
  log:
    output: stderr
    severity: DEBUG

  data_dir: ./data/one-kube

  auth_token: "foo"

  auth_servers:
  - one:3025

auth_service:
  enabled: no

ssh_service:
  enabled: no

proxy_service:
  enabled: no

kubernetes_service:
  enabled: yes
  kubeconfig_file: /Users/nklaassen/src/teletest/kube/kube.config
  listen_addr: 127.0.0.1:3027
