---
version: v3
teleport:
  nodename: one-proxy-1
  log:
    output: stderr
    severity: DEBUG

  data_dir: /Users/nklaassen/src/teletest/data/one-proxy-1

  auth_server: one:3025

  auth_token: "foo"

auth_service:
  enabled: false

ssh_service:
  enabled: false

proxy_service:
  enabled: true

  public_addr: one:3080
  web_listen_addr: 0.0.0.0:4080

  https_keypairs:
    - key_file: /Users/nklaassen/src/teletest/certs/one/key.pem
      cert_file: /Users/nklaassen/src/teletest/certs/one/cert.pem
