---
version: v2
teleport:
  # nodename: one-proxy
  log:
    output: stderr
    severity: DEBUG

  data_dir: ./data/one-proxy

  auth_servers:
    - one:4025

  auth_token: "foo"

auth_service:
  enabled: false

ssh_service:
  enabled: false

proxy_service:
  enabled: true

  web_listen_addr: 0.0.0.0:4080
  public_addr: one:4080

  listen_addr: one:4023
  ssh_public_addr: one:4023

  tunnel_listen_addr: one:4024
  tunnel_public_addr: one:4024

  https_keypairs:
    - key_file: ./certs/one/key.pem
      cert_file: ./certs/one/cert.pem
