version: v3
teleport:
  nodename: one-node
  log:
    output: stderr
    severity: DEBUG
  data_dir: ./data/one-node
  auth_token: foo
  auth_server: one:4025

auth_service:
  enabled: no

proxy_service:
  enabled: no

ssh_service:
  enabled: yes
  listen_addr: 127.0.0.1:3022
  public_addr: 127.0.0.1:3022
  labels:
    region: "us-east-1"
    environment: "staging"
    ctype: "beta"
  commands:
  - name: piped
    command: ['/bin/bash', '-c', 'echo hello | sed "s/h/H/"']
    period: 5m
