teleport:
  nodename: test/one-node
  log:
    output: stderr
    severity: DEBUG

  data_dir: ./data/one-node

  auth_token: foo

  auth_servers:
    - one:4025

auth_service:
  enabled: no

proxy_service:
  enabled: no

ssh_service:
  enabled: yes
  listen_addr: 127.0.0.1:3022
  public_addr: 127.0.0.1:3022
  labels:
    test: test
  commands:
  - name: date
    command: [date]
    period: 5s
