---
version: v3
teleport:
  nodename: one-proxy
  log:
    output: stderr
    severity: DEBUG

  data_dir: ./data/one-proxy
  auth_server: one:4025
  auth_token: "foo"

auth_service:
  enabled: false

ssh_service:
  enabled: false

proxy_service:
  enabled: true

  web_listen_addr: 0.0.0.0:4080
  public_addr: one:4080

  https_keypairs:
    - key_file: ./certs/_.one/key.pem
      cert_file: ./certs/_.one/cert.pem
