# Single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
teleport:
  nodename: one-auth-1
  log:
    output: stderr
    severity: DEBUG

  data_dir: /Users/nklaassen/src/teletest/data/one-auth-1
  storage:
    path: /Users/nklaassen/src/teletest/backend
    type: dir
      #type: etcd
      #peers:
      #- "https://etcd:2379"
      #tls_cert_file: /Users/nklaassen/src/teletest/certs/one/cert.pem
      #tls_key_file: /Users/nklaassen/src/teletest/certs/one/key.pem
      #tls_ca_file: /Users/nklaassen/src/teletest/certs/minica.pem
      #prefix: /teleport/

auth_service:
  enabled: yes

  cluster_name: one

  authentication:
    type: local
    second_factor: off

  tokens:
  - node,proxy,app,kube:foo

  listen_addr: 0.0.0.0:4025

  license_file: /Users/nklaassen/src/teletest/config/license.pem

  ca_key_params:
    pkcs11:
      module_path: /usr/local/Cellar/p11-kit/0.23.22/lib/pkcs11/yubihsm_pkcs11.dylib
      slot_number: 0
      pin: "0001password"

ssh_service:
  enabled: yes
  listen_addr: 0.0.0.0:4022

proxy_service:
  enabled: no
