# requester.yaml
kind: role
version: v5
metadata:
  name: requester
spec:
  allow:
    request:
      roles:
        - access
      search_as_roles:
        - access
    logins:
      - "{{external.asdf}}-test"
---
kind: user
version: v2
metadata:
  name: requester
spec:
  roles:
    - requester
  traits:
    logins: ["nklaassen", "root", "ec2-user"]
