teleport:
  nodename: two-node-iot
  log:
    output: stderr
    severity: DEBUG

  data_dir: ./data/two-node-iot

  auth_token: "foo"

  auth_servers:
  - two:5080

auth_service:
  enabled: no

proxy_service:
  enabled: no

ssh_service:
  enabled: yes
  labels:
    owner: db-admins

app_service:
  enabled: yes
  debug_app: true
  apps:
  - name: "httpbin"
    uri: "http://localhost:80"

kubernetes_service:
  enabled: yes
  kubeconfig_file: /Users/nklaassen/src/teletest/kube/kube.config

db_service:
  enabled: yes
  resources:
  - labels:
      "*": "*"
